name: DMCA Tracker

on:
  schedule:
    - cron: '*/5 * * * *'
  push:
    branches:
      - 'main'
  workflow_dispatch:

concurrency: 
  group: dmca-tracker
  cancel-in-progress: false

jobs:
  track:
    name: Track
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Run tracker.sh
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: |
          ./tracker.sh
